### ISSUE TITLE
Тип не зарегистрирован (Object)}

### ISSUE THREAD

**Issue by SaintMortum** [khorevaa/reflector#32]
На версии oscript 2.0 падает.
Ошибка в строке: 303 / Тип не зарегистрирован (Object)}

**Comment by nixel2007** [comment]
а что передается в рефлектор?

**Comment by SaintMortum** [comment]
Не знаю. Похоже, падает при любом вызове из opm.

**Comment by nixel2007** [comment]
А стек вызовов какой-нибудь есть?

**Comment by SaintMortum** [comment]
Перехватил исключение в РефлекторОбъекта.os:303 и вывел стек вызовов.

{Модуль C:\Program Files\OneScript\lib\reflector\src\Классы\РефлекторОбъекта.os / Ошибка в строке: 334 / Стек трейс:
  C:\Program Files\OneScript\lib\reflector\src\Классы\РефлекторОбъекта.os / Метод РеализованныеМетодыИнтерфейса / Строка 161
    C:\Program Files\OneScript\lib\cli\src\core\Классы\КомандаПриложения.os / Метод ПриСозданииОбъекта / Строка 1283
      C:\Program Files\OneScript\lib\cli\src\core\Классы\КонсольноеПриложение.os / Метод ПриСозданииОбъекта / Строка 209
        C:\Program Files\OneScript\lib\opm\src\cmd\opm.os / Метод ВыполнитьПриложение / Строка 21
          C:\Program Files\OneScript\lib\opm\src\cmd\opm.os / Метод $entry / Строка 53}

**Comment by nixel2007** [comment]
@evilbeaver FYI

**Comment by EvilBeaver** [comment]
@SaintMortum а можешь еще дать из этого перехваченного исключения стектрейс самого движка:

`ИнформацияОбОшибке().ПодробноеОписаниеОшибки()`

**Comment by SaintMortum** [comment]
OneScript.Language.ScriptException: {Модуль C:\Program Files\OneScript\lib\reflector\src\Классы\РефлекторОбъекта.os / Ошибка в строке: 304 / Тип не зарегистрирован (Object)}
                ЭтоСценарийОбъект = ТипЗнч(ОбъектПроверки) = Тип("Сценарий") ИЛИ ТипЗнч(ОбъектПроверки) = Тип("Object");
 ---> OneScript.Commons.RuntimeException: Тип не зарегистрирован (Object)
   at ScriptEngine.Machine.DefaultTypeManager.GetTypeByName(String name)
   at ScriptEngine.Machine.MachineInstance.Type(Int32 arg)
   at ScriptEngine.Machine.MachineInstance.MainCommandLoop()
   --- End of inner exception stack trace ---
   at ScriptEngine.Machine.MachineInstance.MainCommandLoop()
   at ScriptEngine.Machine.MachineInstance.ExecuteCode()

**Comment by EvilBeaver** [comment]
@nixel2007 @artbear по-моему, Тип("Object") это какой-то костыль и/или обход ошибки. Т.е. ругнулось на выражении Тип("Object") т.е. не нашло такой тип. Но оно и в 1.x не должно находить. Может помните, что это за проверка?

**Comment by nixel2007** [comment]
Не помню. Может сценарий из строки?

**Comment by nixel2007** [comment]
@khorevaa

**Comment by EvilBeaver** [comment]
Короче говоря, это ошибка рефлектора. Он не должен обращаться к типу "Object", т.к. такого типа нет
А если платформа (osweb или 1script) его возвращает, то это ошибка платформы. Этот тип не должен выдаваться на уровень bsl
