### ISSUE TITLE
В oscript-library/reflector опечатка в описании библиотеки ("интерфесами")

### ISSUE THREAD

**Issue by kuntashov** [khorevaa/reflector#5]
В oscript-library/reflector опечатка в описании библиотеки:

```
Улучшенная работа с рефлектором и интерфесами
```
(В слове "интерфесами" пропущена "Й")
 
В данном репо все ок.

**Comment by khorevaa** [comment]
@nixel2007 У меня нет прав изменить название в oscript-library/reflector. Внеси изменения

**Comment by nixel2007** [comment]
Поправил
